# Change these first
owner: bbva-openweb # Your GitHub organization or username, where this repository lives
repo: openweb-uptime-services # The name of this repository

sites:
  - name: Openweb Service (PLAY) - Accesses
    url: $OPENWEB_HEALTH_PLAY/accesses
    maxResponseTime: 15000
  - name: Openweb Service (PLAY) - Analytics
    url: $OPENWEB_HEALTH_PLAY/analytics
    maxResponseTime: 15000
  - name: Openweb Service (PLAY) - Average
    url: $OPENWEB_HEALTH_PLAY/average
    maxResponseTime: 15000
  - name: Openweb Service (PLAY) - CDN
    url: $OPENWEB_HEALTH_PLAY/cdn
    maxResponseTime: 15000
  - name: Openweb Service (PLAY) - Comments
    url: $OPENWEB_HEALTH_PLAY/comments
    maxResponseTime: 15000
  - name: Openweb Service (PLAY) - Components
    url: $OPENWEB_HEALTH_PLAY/components
    maxResponseTime: 15000
  - name: Openweb Service (PLAY) - Computes
    url: $OPENWEB_HEALTH_PLAY/computes
    maxResponseTime: 15000
  - name: Openweb Service (PLAY) - Departments
    url: $OPENWEB_HEALTH_PLAY/departments
    maxResponseTime: 15000
  - name: Openweb Service (PLAY) - Deploys
    url: $OPENWEB_HEALTH_PLAY/deploys
    maxResponseTime: 15000
  - name: Openweb Service (PLAY) - Domains
    url: $OPENWEB_HEALTH_PLAY/domains
    maxResponseTime: 15000
  - name: Openweb Service (PLAY) - Dynamo
    url: $OPENWEB_HEALTH_PLAY/dynamo
    maxResponseTime: 15000
  - name: Openweb Service (PLAY) - Jenkins
    url: $OPENWEB_HEALTH_PLAY/jenkins
    maxResponseTime: 15000
  - name: Openweb Service (PLAY) - Form
    url: $OPENWEB_HEALTH_PLAY/form
    maxResponseTime: 15000
  - name: Openweb Service (PLAY) - Likes
    url: $OPENWEB_HEALTH_PLAY/likes
    maxResponseTime: 15000
  - name: Openweb Service (PLAY) - Most Popular
    url: $OPENWEB_HEALTH_PLAY/mostpopulars
    maxResponseTime: 15000
  - name: Openweb Service (PLAY) - Newsletter
    url: $OPENWEB_HEALTH_PLAY/newsletter
    maxResponseTime: 15000
  - name: Openweb Service (PLAY) - Notifications
    url: $OPENWEB_HEALTH_PLAY/notifications
    maxResponseTime: 15000
  - name: Openweb Service (PLAY) - Poll
    url: $OPENWEB_HEALTH_PLAY/poll
    maxResponseTime: 15000
  - name: Openweb Service (PLAY) - Projects
    url: $OPENWEB_HEALTH_PLAY/projects
    maxResponseTime: 15000
  - name: Openweb Service (PLAY) - Proxy
    url: $OPENWEB_HEALTH_PLAY/proxy
    maxResponseTime: 15000
  - name: Openweb Service (PLAY) - Roles
    url: $OPENWEB_HEALTH_PLAY/roles
    maxResponseTime: 15000
  - name: Openweb Service (PLAY) - SAML
    url: $OPENWEB_HEALTH_PLAY/saml
    maxResponseTime: 15000
  - name: Openweb Service (PLAY) - Salesforce
    url: $OPENWEB_HEALTH_PLAY/salesforce
    maxResponseTime: 15000
  - name: Openweb Service (PLAY) - Search
    url: $OPENWEB_HEALTH_PLAY/search
    maxResponseTime: 15000
  - name: Openweb Service (PLAY) - Statistics
    url: $OPENWEB_HEALTH_PLAY/statistics
    maxResponseTime: 15000
  - name: Openweb Service (PLAY) - Tasks
    url: $OPENWEB_HEALTH_PLAY/tasks
    maxResponseTime: 15000
  - name: Openweb Service (PLAY) - Users
    url: $OPENWEB_HEALTH_PLAY/users
    maxResponseTime: 15000
  - name: Openweb Service (PLAY) - Visits
    url: $OPENWEB_HEALTH_PLAY/visits
    maxResponseTime: 15000
  - name: Openweb Service (PLAY) - Watermark
    url: $OPENWEB_HEALTH_PLAY/watermark
    maxResponseTime: 15000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime-services.openweb.bbva
  # baseUrl: /openweb-uptime-services
  logoUrl: https://cdn.openweb.bbva/logos/openweb/small.png
  favicon: https://cdn.openweb.bbva/favicon/bbva/favicon-96x96.png
  name: Openweb Services Uptime
  introTitle: "**Openweb Services Uptime** is the uptime monitor and status page for the services provided by Openweb."
  introMessage: This is a status page which uses _real-time_ data (every site is checked every 60 minutes). You can check the response time of every monitored service.
  themeUrl: https://cdn.openweb.bbva/css/status/openweb-theme.css
  navbar:
    - title: Status
      href: /
    - title: Openweb Control Panel
      href: https://webpublicas.bbva.com/
  metaTags:
    - name: "robots"
      content: "noindex"
  robotsText: "User-agent: * \n Disallow: /"

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 * * * *"
  
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
