# Change these first
owner: bbva-openweb # Your GitHub organization or username, where this repository lives
repo: uptime-services # The name of this repository

sites:
  - name: Panel de Openweb
    url: https://webpublicas.bbva.com/
  - name: Openweb Service - Accesses
    url: $OPENWEB_HEALTH_LIVE/accesses
    maxResponseTime: 15000
  - name: Openweb Service - Analytics
    url: $OPENWEB_HEALTH_LIVE/analytics
    maxResponseTime: 15000
  - name: Openweb Service - Average
    url: $OPENWEB_HEALTH_LIVE/averages
    maxResponseTime: 15000
  - name: Openweb Service - CDN
    url: $OPENWEB_HEALTH_LIVE/cdn
    maxResponseTime: 15000
  - name: Openweb Service - Comments
    url: $OPENWEB_HEALTH_LIVE/comments
    maxResponseTime: 15000
  - name: Openweb Service - Components
    url: $OPENWEB_HEALTH_LIVE/components
    maxResponseTime: 15000
  - name: Openweb Service - Computes
    url: $OPENWEB_HEALTH_LIVE/computes
    maxResponseTime: 15000
  - name: Openweb Service - Departments
    url: $OPENWEB_HEALTH_LIVE/departments
    maxResponseTime: 15000
  - name: Openweb Service - Deploys
    url: $OPENWEB_HEALTH_LIVE/deploys
    maxResponseTime: 15000
  - name: Openweb Service - Domains
    url: $OPENWEB_HEALTH_LIVE/domains
    maxResponseTime: 15000
  - name: Openweb Service - Dynamo
    url: $OPENWEB_HEALTH_LIVE/dynamo
    maxResponseTime: 15000
  - name: Openweb Service - Jenkins
    url: $OPENWEB_HEALTH_LIVE/jenkins
    maxResponseTime: 15000
  - name: Openweb Service - Form
    url: $OPENWEB_HEALTH_LIVE/form
    maxResponseTime: 15000
  - name: Openweb Service - Likes
    url: $OPENWEB_HEALTH_LIVE/likes
    maxResponseTime: 15000
  - name: Openweb Service - Most Popular
    url: $OPENWEB_HEALTH_LIVE/mostpopulars
    maxResponseTime: 15000
  - name: Openweb Service - Newsletter
    url: $OPENWEB_HEALTH_LIVE/newsletter
    maxResponseTime: 15000
  - name: Openweb Service - Notifications
    url: $OPENWEB_HEALTH_LIVE/notifications
    maxResponseTime: 15000
  - name: Openweb Service - Poll
    url: $OPENWEB_HEALTH_LIVE/poll
    maxResponseTime: 15000
  - name: Openweb Service - Projects
    url: $OPENWEB_HEALTH_LIVE/projects
    maxResponseTime: 15000
  - name: Openweb Service - Proxy
    url: $OPENWEB_HEALTH_LIVE/proxy
    maxResponseTime: 15000
  - name: Openweb Service - Roles
    url: $OPENWEB_HEALTH_LIVE/roles
    maxResponseTime: 15000
  - name: Openweb Service - SAML
    url: $OPENWEB_HEALTH_LIVE/saml
    maxResponseTime: 15000
  - name: Openweb Service - Salesforce
    url: $OPENWEB_HEALTH_LIVE/salesforce
    maxResponseTime: 15000
  - name: Openweb Service - Search
    url: $OPENWEB_HEALTH_LIVE/search
    maxResponseTime: 15000
  - name: Openweb Service - Statistics
    url: $OPENWEB_HEALTH_LIVE/statistics
    maxResponseTime: 15000
  - name: Openweb Service - Tasks
    url: $OPENWEB_HEALTH_LIVE/tasks
    maxResponseTime: 15000
  - name: Openweb Service - Users
    url: $OPENWEB_HEALTH_LIVE/users
    maxResponseTime: 15000
  - name: Openweb Service - Watermark
    url: $OPENWEB_HEALTH_LIVE/watermark
    maxResponseTime: 15000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.openweb.bbva
  # baseUrl: /uptime-services
  logoUrl: https://cdn.openweb.bbva/logos/openweb/small.png
  favicon: https://cdn.openweb.bbva/favicon/bbva/favicon-96x96.png
  name: Openweb Services Uptime
  introTitle: "**Openweb Services Uptime** is the uptime monitor and status page for the services provided by Openweb."
  introMessage: This is a status page which uses _real-time_ data (every site is checked every 60 minutes). You can check the response time of every monitored service.
  themeUrl: https://cdn.openweb.bbva/css/status/openweb-theme.css
  navbar:
    - title: Status
      href: /
    - title: Openweb Control Panel
      href: https://webpublicas.bbva.com/
  metaTags:
    - name: "robots"
      content: "noindex"
  robotsText: "User-agent: * \n Disallow: /"

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
